name: hugo CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 1   

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true 
          
      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONEL_ACCESS_TOKEN }}
          external_repository: projectlegionos/projectlegionos.github.io
          publish_branch: master
          publish_dir: ./public
          user_name: 'projectlegionos'
          user_email: 'projectlegionos@gmail.com'
